/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.imageio.ImageIO;
import java.net.URL;
import java.util.Base64;
import java.awt.image.BufferedImage;
import javax.swing.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import app.GoogleBooksScraper.SearchResult;
import java.util.Base64;
import java.awt.Desktop;


public class searchpage extends JPanel {
    private YourApp app = (YourApp) SwingUtilities.getWindowAncestor(this);
    private List<SearchResult> results;
    //YourApp yourapp =  new YourApp();

    public searchpage(YourApp app, List<SearchResult> results) {
        this.results = results;
        this.app = app;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        searchbar = new javax.swing.JPanel();
        search_box = new app.textbx(26);
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        titles = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultt4 = new javax.swing.JPanel();
        resultt5 = new rectro(47);
        resultt6 = new rectro(47);
        resultt7 = new rectro(47);
        resultt8 = new rectro(47);
        resultt9 = new rectro(47);
        img5 = new javax.swing.JLabel();
        title5 = new javax.swing.JLabel();
        cate5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        img6 = new javax.swing.JLabel();
        title6 = new javax.swing.JLabel();
        cate6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        img7 = new javax.swing.JLabel();
        title7 = new javax.swing.JLabel();
        cate7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        img8 = new javax.swing.JLabel();
        title8 = new javax.swing.JLabel();
        cate8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        img9 = new javax.swing.JLabel();
        title9 = new javax.swing.JLabel();
        cate9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(230, 230, 230));

        searchbar.setBackground(new java.awt.Color(11, 11, 11));

        search_box.setForeground(new java.awt.Color(11, 11, 11));
        search_box.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        search_box.setOpaque(false);
        search_box.setBorder(javax.swing.BorderFactory.createCompoundBorder(search_box.getBorder(),javax.swing.BorderFactory.createEmptyBorder(5, 10, 7, 10)));
        search_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //search.redirect(searchpage.this,search_box.getText());
            }
        });

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        
        
        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 0, 29)); // NOI18N
        jLabel5.setText("🔍");
        jLabel5.setForeground(Color.WHITE);
        jLabel5.setBackground(new java.awt.Color(11,11,11));

        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new MouseAdapter() { 
            @Override
            public void mouseClicked (MouseEvent e) {              
                //search.redirect(searchpage.this,search_box.getText());}
        }});

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 26)); // NOI18N
        jLabel7.setText("←");
        jLabel7.setForeground(Color.WHITE);
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new MouseAdapter() { public void mouseClicked(MouseEvent e) { app.goBack(); } });
        
        javax.swing.GroupLayout searchbarLayout = new javax.swing.GroupLayout(searchbar);
        searchbar.setLayout(searchbarLayout);
        searchbarLayout.setHorizontalGroup(
            searchbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchbarLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(300, 300, 300)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_box, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(437, Short.MAX_VALUE))
        );
        searchbarLayout.setVerticalGroup(
            searchbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchbarLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(searchbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_box)
                    .addGroup(searchbarLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        titles.setFont(new java.awt.Font("Inter", 0, 48)); // NOI18N
        titles.setText("Titles");
        titles.setPreferredSize(new java.awt.Dimension(200, 55));

        jScrollPane1.setBorder(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 500));

        resultt4.setBackground(new java.awt.Color(230, 230, 230));
        resultt4.setForeground(new java.awt.Color(230, 230, 230));
        // result4.setOpaque(false);

        
        resultt5.setBackground(new java.awt.Color(255,255,255));
        resultt5.setPreferredSize(new java.awt.Dimension(300, 168));
        resultt5.setOpaque(false);

        //img5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/download.jpg"))); // NOI18N

        //img5
        SearchResult result = results.get(0);
        try {
            String imageurl = result.getimageurl();
            if(imageurl != null){
                URI imageUrl = new URI(imageurl);
                ImageIcon originalIcon = new ImageIcon(imageUrl.toURL());
                Image scaledImage = originalIcon.getImage().getScaledInstance(113, 180, Image.SCALE_DEFAULT);
                ImageIcon icon = new ImageIcon(scaledImage);            
                img5.setIcon(icon);}

                resultt5.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        try {
                            Desktop.getDesktop().browse(new URI(result.getLinkText()));
                        } catch (IOException | URISyntaxException e1) {
                            e1.printStackTrace();
                        }
                    }
                });
            title5.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
            title5.setText(result.getTitle());
            title5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            title5.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    title5MouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    title5MouseExited(evt);
                }
            });

            cate5.setText(result.getAuthor()+ "    " + result.getyear());
            jLabel1.setText("<html>"+result.getdescription()+"<html>");

        } catch (URISyntaxException | IOException e) {
            e.printStackTrace();
        }

        javax.swing.GroupLayout result5Layout = new javax.swing.GroupLayout(resultt5);
        resultt5.setLayout(result5Layout);
        result5Layout.setHorizontalGroup(
            result5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(img5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(result5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title5, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cate5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        result5Layout.setVerticalGroup(
            result5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, result5Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(result5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(result5Layout.createSequentialGroup()
                        .addComponent(title5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cate5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(img5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        resultt6.setBackground(new java.awt.Color(255, 255, 255));
        resultt6.setPreferredSize(new java.awt.Dimension(1016, 168));
        resultt6.setOpaque(false);



        //img6
        SearchResult result1 = results.get(1);
        try {
            String imageurl = result1.getimageurl();
            if(imageurl != null){
            URI imageUrl = new URI(imageurl);
            ImageIcon originalIcon = new ImageIcon(imageUrl.toURL());
            Image scaledImage = originalIcon.getImage().getScaledInstance(113, 180, Image.SCALE_DEFAULT);
            ImageIcon icon = new ImageIcon(scaledImage);            
            img6.setIcon(icon);}
        
            resultt6.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    try {
                        Desktop.getDesktop().browse(new URI(result1.getLinkText()));
                    } catch (IOException | URISyntaxException e1){
                        e1.printStackTrace();
                    }
                }
            });

            title6.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
            title6.setText(result1.getTitle());
            title6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            title6.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    title6MouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    title6MouseExited(evt);
                }
            });

            cate6.setText(result1.getAuthor()+ "   "+ result1.getyear());

            jLabel2.setText("<html>"+ result1.getdescription()+"<html>");

            } catch (URISyntaxException | IOException e) {
                e.printStackTrace();
            }

        javax.swing.GroupLayout result6Layout = new javax.swing.GroupLayout(resultt6);
        resultt6.setLayout(result6Layout);
        result6Layout.setHorizontalGroup(
            result6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(img6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(result6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title6, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cate6)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(599, Short.MAX_VALUE))
        );
        result6Layout.setVerticalGroup(
            result6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result6Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(result6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(result6Layout.createSequentialGroup()
                        .addComponent(title6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cate6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(result6Layout.createSequentialGroup()
                        .addComponent(img6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(17, Short.MAX_VALUE))))
        );

        // ImageIcon imageIcon = new ImageIcon(new ImageIcon(getClass().getResource("/Image/download.jpg"))
        //     .getImage().getScaledInstance(113, 180, Image.SCALE_DEFAULT));

        // img6.setIcon(imageIcon);
        // img6.getAccessibleContext().setAccessibleDescription("");



        resultt7.setBackground(new java.awt.Color(255, 255, 255));
        resultt7.setPreferredSize(new java.awt.Dimension(1016, 168));
        resultt7.setOpaque(false);
        //img5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/download.jpg"))); // NOI18N

        //img7
        SearchResult result2 = results.get(2);

        try {
            String imageurl = result2.getimageurl();
            if(imageurl != null){
            URI imageUrl = new URI(imageurl);
            ImageIcon originalIcon = new ImageIcon(imageUrl.toURL());
            Image scaledImage = originalIcon.getImage().getScaledInstance(113, 180, Image.SCALE_DEFAULT);
            ImageIcon icon = new ImageIcon(scaledImage);            
            img7.setIcon(icon);}
        
            resultt7.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    try {
                        Desktop.getDesktop().browse(new URI(result2.getLinkText()));
                    } catch (IOException | URISyntaxException e1) {
                        e1.printStackTrace();
                    }
                }
            });

            title7.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
            title7.setText(result2.getTitle());
            title7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            title7.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    title7MouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    title7MouseExited(evt);
                }
            });

            cate7.setText(result2.getAuthor()+"   "+ result2.getyear());
            jLabel4.setText("<html>"+result2.getdescription()+"<html>");

            } catch (URISyntaxException | IOException e) {
                e.printStackTrace();
            }

        javax.swing.GroupLayout result7Layout = new javax.swing.GroupLayout(resultt7);
        resultt7.setLayout(result7Layout);
        result7Layout.setHorizontalGroup(
            result7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(img7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(result7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title7, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cate7)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(595, Short.MAX_VALUE))
        );
        result7Layout.setVerticalGroup(
            result7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result7Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(result7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, result7Layout.createSequentialGroup()
                        .addComponent(title7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cate7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, result7Layout.createSequentialGroup()
                        .addComponent(img7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );

        resultt8.setBackground(new java.awt.Color(255, 255, 255));
        resultt8.setOpaque(false);
        //img7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/download.jpg"))); // NOI18N
        //img8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/download.jpg"))); // NOI18N

        //img8
        SearchResult result3 = results.get(3);
        try {
            String imageurl = result3.getimageurl();
            if(imageurl != null){
            URI imageUrl = new URI(imageurl);
            ImageIcon originalIcon = new ImageIcon(imageUrl.toURL());
            Image scaledImage = originalIcon.getImage().getScaledInstance(113, 180, Image.SCALE_DEFAULT);
            ImageIcon icon = new ImageIcon(scaledImage);            
            img8.setIcon(icon);}

            resultt8.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    try {
                        Desktop.getDesktop().browse(new URI(result3.getLinkText()));
                    } catch (IOException | URISyntaxException e1) {
                        e1.printStackTrace();
                    }
                }
            });

        title8.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        title8.setText(result3.getTitle());
        title8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        title8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                title8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                title8MouseExited(evt);
            }
        });

        cate8.setText(result3.getAuthor()+"   "+result3.getyear());

        jLabel3.setText("<html>"+result3.getdescription()+"<html>");
        } catch (URISyntaxException | IOException e) {
            e.printStackTrace();
        }

        javax.swing.GroupLayout result8Layout = new javax.swing.GroupLayout(resultt8);
        resultt8.setLayout(result8Layout);
        result8Layout.setHorizontalGroup(
            result8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(img8, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(result8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title8, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cate8)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(597, Short.MAX_VALUE))
        );
        result8Layout.setVerticalGroup(
            result8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result8Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(result8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(result8Layout.createSequentialGroup()
                        .addComponent(title8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(cate8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(img8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        resultt9.setBackground(new java.awt.Color(255, 255, 255));
        resultt9.setPreferredSize(new java.awt.Dimension(427, 168));
        resultt9.setOpaque(false);

        //img9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/download.jpg"))); // NOI18N

        //img9
        SearchResult result4 = results.get(4);

        try {
            String imageurl = result4.getimageurl();
            if(imageurl != null){
            URI imageUrl = new URI(imageurl);
            ImageIcon originalIcon = new ImageIcon(imageUrl.toURL());
            Image scaledImage = originalIcon.getImage().getScaledInstance(113, 180, Image.SCALE_DEFAULT);
            ImageIcon icon = new ImageIcon(scaledImage);            
            img9.setIcon(icon);}
            
            resultt9.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    try {
                        Desktop.getDesktop().browse(new URI(result4.getLinkText()));
                    } catch (IOException | URISyntaxException e1) {
                        e1.printStackTrace();
                    }
                }
            });

        title9.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        title9.setText(result4.getTitle());
        title9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        title9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                title9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                title9MouseExited(evt);
            }
        });

        cate9.setText(result4.getAuthor()+"   "+result4.getyear());

        jLabel6.setText("<html>"+result4.getdescription()+"<html>");
        } catch (URISyntaxException | IOException e) {
            e.printStackTrace();
        }

        javax.swing.GroupLayout result9Layout = new javax.swing.GroupLayout(resultt9);
        resultt9.setLayout(result9Layout);
        result9Layout.setHorizontalGroup(
            result9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result9Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(img9, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(result9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title9, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cate9)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(595, Short.MAX_VALUE))
        );
        result9Layout.setVerticalGroup(
            result9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result9Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(result9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, result9Layout.createSequentialGroup()
                        .addComponent(title9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cate9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, result9Layout.createSequentialGroup()
                        .addComponent(img9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout result4Layout = new javax.swing.GroupLayout(resultt4);
        resultt4.setLayout(result4Layout);
        result4Layout.setHorizontalGroup(
            result4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(result4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(result4Layout.createSequentialGroup()
                        .addGroup(result4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(resultt6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resultt8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resultt7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resultt9, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
                            .addComponent(resultt5, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        result4Layout.setVerticalGroup(
            result4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(resultt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultt9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(resultt4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchbar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titles, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(titles, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(14);
        jScrollPane1.getVerticalScrollBar().setPreferredSize(new Dimension(0,0));
        jScrollPane1.setBackground(new java.awt.Color(230,230,230));
        jScrollPane1.setForeground(new java.awt.Color(230,230,230));
        jScrollPane1.getHorizontalScrollBar().setPreferredSize(new Dimension(0,0));

        
    }// </editor-fold>//GEN-END:initComponents

    private void search_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_boxActionPerformed

    private void title6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title6MouseEntered
    title6.setForeground(new Color(153,153,153));        // TODO add your handling code here:
    }//GEN-LAST:event_title6MouseEntered

    private void title6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title6MouseExited
      title6.setForeground(new Color(0,0,0));    // TODO add your handling code here:
    }//GEN-LAST:event_title6MouseExited

    private void title5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title5MouseEntered
   title5.setForeground(new Color(153,153,153));         // TODO add your handling code here:
    }//GEN-LAST:event_title5MouseEntered

    private void title5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title5MouseExited
   title5.setForeground(new Color(0,0,0));          // TODO add your handling code here:
    }//GEN-LAST:event_title5MouseExited

    private void title8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title8MouseEntered
title8.setForeground(new Color(153,153,153));          // TODO add your handling code here:
    }//GEN-LAST:event_title8MouseEntered

    private void title8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title8MouseExited
title8.setForeground(new Color(0,0,0));          // TODO add your handling code here:
    }//GEN-LAST:event_title8MouseExited

    private void title7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title7MouseEntered
title7.setForeground(new Color(153,153,153));          // TODO add your handling code here:
    }//GEN-LAST:event_title7MouseEntered

    private void title7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title7MouseExited
title7.setForeground(new Color(0,0,0));          // TODO add your handling code here:
    }//GEN-LAST:event_title7MouseExited

    private void title9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title9MouseEntered
title9.setForeground(new Color(153,153,153));          // TODO add your handling code here:
    }//GEN-LAST:event_title9MouseEntered

    private void title9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title9MouseExited
title9.setForeground(new Color(0,0,0));          // TODO add your handling code here:
    }//GEN-LAST:event_title9MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    //     /* Create and display the form */
    //     java.awt.EventQueue.invokeLater(new Runnable() {
    //         public void run() {
    //             new searchpage().setVisible(true);
    //         }
    //     });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cate5;
    private javax.swing.JLabel cate6;
    private javax.swing.JLabel cate7;
    private javax.swing.JLabel cate8;
    private javax.swing.JLabel cate9;
    private javax.swing.JLabel img5;
    private javax.swing.JLabel img6;
    private javax.swing.JLabel img7;
    private javax.swing.JLabel img8;
    private javax.swing.JLabel img9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel resultt4;
    private javax.swing.JPanel resultt5;
    private javax.swing.JPanel resultt6;
    private javax.swing.JPanel resultt7;
    private javax.swing.JPanel resultt8;
    private javax.swing.JPanel resultt9;
    private javax.swing.JTextField search_box;
    private javax.swing.JPanel searchbar;
    private javax.swing.JLabel title5;
    private javax.swing.JLabel title6;
    private javax.swing.JLabel title7;
    private javax.swing.JLabel title8;
    private javax.swing.JLabel title9;
    private javax.swing.JLabel titles;
    // End of variables declaration//GEN-END:variables
}
